# Generated by Django 4.2.1 on 2024-09-30 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentlikes',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog_app.blogcomments'),
        ),
        migrations.AlterUniqueTogether(
            name='blogcommentlikes',
            unique_together={('comment', 'user')},
        ),
    ]
